#!/usr/bin/env bash
# Apply Cloudflare WARP domain-fallback + split-tunnel exclusion rules.
# Domestic (.cn / major Chinese) sites bypass WARP; foreign LLM/search/blocked
# sites go through the WARP tunnel by default.
#   DNS fallback   = SUFFIX match -> bare "abc.com" covers subdomains (NO wildcard)
#   Tunnel exclude = DOMAIN match -> subdomains need "*.abc.com"
#   "cn" alone covers all .cn at any level (no per-site .cn entries needed)
# Requires: warp-cli installed, WARP registered, run as root.

set -euo pipefail
if ! command -v warp-cli >/dev/null 2>&1; then
  echo "warp-cli not found. Install Cloudflare WARP client first." >&2
  exit 1
fi

# DNS fallback list (bare homepages only; suffix match covers subdomains) + "cn"
fallback=(\n  '126.com'
  '163.com'
  'abchina.com'
  'alipay.com'
  'aliyun.com'
  'aliyuncs.com'
  'amap.com'
  'baichuan-ai.com'
  'baidu.com'
  'bankcomm.com'
  'bankofchina.com'
  'bilibili.com'
  'bytedance.com'
  'ccb.com'
  'cctv.com'
  'chinaz.com'
  'cmbchina.com'
  'cn'
  'cnblogs.com'
  'csdn.net'
  'ctrip.com'
  'deepseek.ai'
  'deepseek.com'
  'dianping.com'
  'didiglobal.com'
  'dingtalk.com'
  'docer.com'
  'douban.com'
  'douyin.com'
  'douyu.com'
  'fliggy.com'
  'foxmail.com'
  'haier.com'
  'huaweicloud.com'
  'huya.com'
  'icbc.com'
  'iqiyi.com'
  'jd.com'
  'jianshu.com'
  'jingdong.com'
  'kuaishou.com'
  'kugou.com'
  'lingyiwanwu.com'
  'meituan.com'
  'mgtv.com'
  'mi.com'
  'minimax.io'
  'myqcloud.com'
  'netease.com'
  'oschina.net'
  'pinduoduo.com'
  'qq.com'
  'qunar.com'
  'qwen.ai'
  'sogou.com'
  'sohu.com'
  'stepfun.com'
  'suning.com'
  'taobao.com'
  'tcl.com'
  'tencentcloud.com'
  'tmall.com'
  'toutiao.com'
  'trip.com'
  'vip.com'
  'volcengine.com'
  'weibo.com'
  'weixin.qq.com'
  'wps.com'
  'xianyu.com'
  'xiaohongshu.com'
  'xinhuanet.com'
  'yi.com'
  'yinyuetai.com'
  'youku.com'
  'zhihu.com'\n)

# Tunnel exclude list (homepage + *.homepage) + "cn"
exclude=(\n  '*.126.com'
  '*.163.com'
  '*.abchina.com'
  '*.alipay.com'
  '*.aliyun.com'
  '*.aliyuncs.com'
  '*.amap.com'
  '*.baichuan-ai.com'
  '*.baidu.com'
  '*.bankcomm.com'
  '*.bankofchina.com'
  '*.bilibili.com'
  '*.bytedance.com'
  '*.ccb.com'
  '*.cctv.com'
  '*.chinaz.com'
  '*.cmbchina.com'
  '*.cnblogs.com'
  '*.csdn.net'
  '*.ctrip.com'
  '*.deepseek.ai'
  '*.deepseek.com'
  '*.dianping.com'
  '*.didiglobal.com'
  '*.dingtalk.com'
  '*.docer.com'
  '*.douban.com'
  '*.douyin.com'
  '*.douyu.com'
  '*.fliggy.com'
  '*.foxmail.com'
  '*.haier.com'
  '*.huaweicloud.com'
  '*.huya.com'
  '*.icbc.com'
  '*.iqiyi.com'
  '*.jd.com'
  '*.jianshu.com'
  '*.jingdong.com'
  '*.kuaishou.com'
  '*.kugou.com'
  '*.lingyiwanwu.com'
  '*.meituan.com'
  '*.mgtv.com'
  '*.mi.com'
  '*.minimax.io'
  '*.myqcloud.com'
  '*.netease.com'
  '*.oschina.net'
  '*.pinduoduo.com'
  '*.qq.com'
  '*.qunar.com'
  '*.qwen.ai'
  '*.sogou.com'
  '*.sohu.com'
  '*.stepfun.com'
  '*.suning.com'
  '*.taobao.com'
  '*.tcl.com'
  '*.tencentcloud.com'
  '*.tmall.com'
  '*.toutiao.com'
  '*.trip.com'
  '*.vip.com'
  '*.volcengine.com'
  '*.weibo.com'
  '*.weixin.qq.com'
  '*.wps.com'
  '*.xianyu.com'
  '*.xiaohongshu.com'
  '*.xinhuanet.com'
  '*.yi.com'
  '*.yinyuetai.com'
  '*.youku.com'
  '*.zhihu.com'
  '126.com'
  '163.com'
  'abchina.com'
  'alipay.com'
  'aliyun.com'
  'aliyuncs.com'
  'amap.com'
  'baichuan-ai.com'
  'baidu.com'
  'bankcomm.com'
  'bankofchina.com'
  'bilibili.com'
  'bytedance.com'
  'ccb.com'
  'cctv.com'
  'chinaz.com'
  'cmbchina.com'
  'cnblogs.com'
  'csdn.net'
  'ctrip.com'
  'deepseek.ai'
  'deepseek.com'
  'dianping.com'
  'didiglobal.com'
  'dingtalk.com'
  'docer.com'
  'douban.com'
  'douyin.com'
  'douyu.com'
  'fliggy.com'
  'foxmail.com'
  'haier.com'
  'huaweicloud.com'
  'huya.com'
  'icbc.com'
  'iqiyi.com'
  'jd.com'
  'jianshu.com'
  'jingdong.com'
  'kuaishou.com'
  'kugou.com'
  'lingyiwanwu.com'
  'meituan.com'
  'mgtv.com'
  'mi.com'
  'minimax.io'
  'myqcloud.com'
  'netease.com'
  'oschina.net'
  'pinduoduo.com'
  'qq.com'
  'qunar.com'
  'qwen.ai'
  'sogou.com'
  'sohu.com'
  'stepfun.com'
  'suning.com'
  'taobao.com'
  'tcl.com'
  'tencentcloud.com'
  'tmall.com'
  'toutiao.com'
  'trip.com'
  'vip.com'
  'volcengine.com'
  'weibo.com'
  'weixin.qq.com'
  'wps.com'
  'xianyu.com'
  'xiaohongshu.com'
  'xinhuanet.com'
  'yi.com'
  'yinyuetai.com'
  'youku.com'
  'zhihu.com'\n)

echo "Applying DNS fallback list ($((${#fallback[@]})) entries)..."
for d in "${fallback[@]}"; do warp-cli dns fallback add "$d" >/dev/null 2>&1 || true; done

echo "Applying tunnel exclude list ($((${#exclude[@]})) entries)..."
for d in "${exclude[@]}"; do warp-cli tunnel host add "$d" >/dev/null 2>&1 || true; done

echo "=== Done. Restart WARP: warp-cli disconnect && warp-cli connect ==="