# Requires: Cloudflare WARP client installed, warp-cli in PATH, run as Administrator
# Purpose: Apply domain-fallback + split-tunnel exclusion rules so that
#          domestic (.cn / major Chinese sites) bypass WARP, while foreign
#          LLM / search / blocked sites go through the WARP tunnel by default.

$ErrorActionPreference = 'SilentlyContinue'

function Test-Warp {
    $reg = warp-cli registration show 2>&1
    if ($LASTEXITCODE -ne 0 -or ($reg -match 'not registered' -or $reg -match 'error')) {
        Write-Warning "warp-cli 未就绪或未注册，请先完成 WARP 注册 (warp-cli registration new)。"
        exit 1
    }
}

function Add-Fallback { param([string[]]$list)
    $n = 0
    foreach ($d in $list) { if ((warp-cli dns fallback add $d 2>&1) -match 'Success') { $n++ } }
    Write-Host "DNS 回退: 已添加 $n / $($list.Count)"
}

function Add-Exclude { param([string[]]$list)
    $n = 0
    foreach ($d in $list) { if ((warp-cli tunnel host add $d 2>&1) -match 'Success') { $n++ } }
    Write-Host "隧道排除: 已添加 $n / $($list.Count)"
}

Test-Warp

# ===== DNS 回退列表 (后缀匹配: 裸主域已覆盖子域) =====
$fallback = @(
    '126.com',
    '163.com',
    '2345.com',
    '37.com',
    '4399.com',
    'abchina.com',
    'acfun.com',
    'alibabacloud.com',
    'alicdn.com',
    'alipay.com',
    'alipayobjects.com',
    'aliyun.com',
    'aliyuncs.com',
    'aliyundrive.com',
    'amap.com',
    'antgroup.com',
    'ark.cn-beijing.volces.com',
    'baichuan-ai.com',
    'baidu.com',
    'baidubce.com',
    'baiducloud.com',
    'baiducontent.com',
    'bankcomm.com',
    'bankofchina.com',
    'bdimg.com',
    'bdstatic.com',
    'bilibili.com',
    'bilibili.tv',
    'bytedance.com',
    'cctv.com',
    'chinaz.com',
    'cmbchina.com',
    'cn',
    'cnbce.com',
    'cnblogs.com',
    'csdn.net',
    'ctrip.com',
    'deepseek.ai',
    'deepseek.com',
    'dianping.com',
    'didichuxing.com',
    'didiglobal.com',
    'dingtalk.com',
    'docer.com',
    'douban.com',
    'douyin.com',
    'douyu.com',
    'etao.com',
    'feishu.com',
    'fliggy.com',
    'foxmail.com',
    'hao123.com',
    'haosou.com',
    'huaweicloud.com',
    'huya.com',
    'hwclouds.com',
    'iqiyi.com',
    'iqiyipic.com',
    'jd.com',
    'jianshu.com',
    'jingdong.com',
    'jinritemai.com',
    'kingsoft.com',
    'kuaishou.com',
    'kugou.com',
    'le.com',
    'lenovocn.com',
    'licai.com',
    'lingyiwanwu.com',
    'meituan.com',
    'mgtv.com',
    'mi.com',
    'minimax.io',
    'myqcloud.com',
    'netease.com',
    'oschina.net',
    'pinduoduo.com',
    'qiniu.com',
    'qiniucdn.com',
    'qq.com',
    'qunar.com',
    'qwen.ai',
    'so.com',
    'sogou.com',
    'sohu.com',
    'stepfun.com',
    'suning.com',
    'taobao.com',
    'tcl.com',
    'tencentcloud.com',
    'tmall.com',
    'toutiao.com',
    'trip.com',
    'tudou.com',
    'ucweb.com',
    'vip.com',
    'volcengine.com',
    'wechat.com',
    'weibo.com',
    'wps.com',
    'xianyu.com',
    'xiaohongshu.com',
    'xinhuanet.com',
    'yi.com',
    'yinyuetai.com',
    'youku.com',
    'yy.com',
    'zhangzha.com',
    'zhihu.com'
)

# ===== 隧道排除列表 (域名匹配: 子域需显式或用 *. 通配) =====
$exclude  = @(
    '126.com',
    '163.com',
    '2345.com',
    '37.com',
    '4399.com',
    'abchina.com',
    'acfun.com',
    'alibabacloud.com',
    'alicdn.com',
    'alipay.com',
    'alipayobjects.com',
    'aliyun.com',
    'aliyuncs.com',
    'aliyundrive.com',
    'amap.com',
    'antgroup.com',
    'ark.cn-beijing.volces.com',
    'baichuan-ai.com',
    'baidu.com',
    'baidubce.com',
    'baiducloud.com',
    'baiducontent.com',
    'bankcomm.com',
    'bankofchina.com',
    'bdimg.com',
    'bdstatic.com',
    'bilibili.com',
    'bilibili.tv',
    'bytedance.com',
    'cctv.com',
    'chat.deepseek.com',
    'chinaz.com',
    'cmbchina.com',
    'cn',
    'cnbce.com',
    'cnblogs.com',
    'csdn.net',
    'ctrip.com',
    'deepseek.ai',
    'deepseek.com',
    'dianping.com',
    'didichuxing.com',
    'didiglobal.com',
    'dingtalk.com',
    'docer.com',
    'douban.com',
    'douyin.com',
    'douyu.com',
    'etao.com',
    'feishu.com',
    'fliggy.com',
    'foxmail.com',
    'hao123.com',
    'haosou.com',
    'huaweicloud.com',
    'huya.com',
    'hwclouds.com',
    'iqiyi.com',
    'iqiyipic.com',
    'jd.com',
    'jianshu.com',
    'jingdong.com',
    'jinritemai.com',
    'jr.jd.com',
    'kingsoft.com',
    'kuaishou.com',
    'kugou.com',
    'lbs.amap.com',
    'le.com',
    'lenovocn.com',
    'licai.com',
    'lingyiwanwu.com',
    'mail.163.com',
    'mail.qq.com',
    'map.baidu.com',
    'meituan.com',
    'mgtv.com',
    'mi.com',
    'minimax.io',
    'music.163.com',
    'myqcloud.com',
    'netease.com',
    'oschina.net',
    'oss-cn-hangzhou.aliyuncs.com',
    'pinduoduo.com',
    'qiniu.com',
    'qiniucdn.com',
    'qq.com',
    'qunar.com',
    'qwen.ai',
    'qzone.qq.com',
    'so.com',
    'sogou.com',
    'sohu.com',
    'stepfun.com',
    'suning.com',
    'taobao.com',
    'tcl.com',
    'tencentcloud.com',
    'tieba.baidu.com',
    'tmall.com',
    'tongyi.aliyun.com',
    'toutiao.com',
    'trip.com',
    'tudou.com',
    'ucweb.com',
    'v.qq.com',
    'vip.com',
    'volcengine.com',
    'wechat.com',
    'weibo.com',
    'weixin.qq.com',
    'wps.com',
    'xianyu.com',
    'xiaohongshu.com',
    'xinhuanet.com',
    'yi.com',
    'yinyuetai.com',
    'youku.com',
    'yy.com',
    'zhangzha.com',
    'zhihu.com'
)

Add-Fallback $fallback
Add-Exclude  $exclude

Write-Host "=== 完成。建议重启 WARP 使规则全量生效 ==="
Write-Host "warp-cli disconnect ; warp-cli connect"
