#!/usr/bin/env bash
# Apply Cloudflare WARP domain-fallback + split-tunnel exclusion rules.
# Domestic (.cn / major Chinese) sites bypass WARP; foreign LLM/search/blocked
# sites go through the WARP tunnel by default.
# Requires: warp-cli installed, WARP registered, run as root.

set -euo pipefail

if ! command -v warp-cli >/dev/null 2>&1; then
  echo "warp-cli 未找到，请先安装 Cloudflare WARP 客户端。" >&2
  exit 1
fi

# ===== DNS fallback list (suffix match: bare apex covers subdomains) =====
fallback=(\n  '126.com'
  '163.com'
  '2345.com'
  '37.com'
  '4399.com'
  'abchina.com'
  'acfun.com'
  'alibabacloud.com'
  'alicdn.com'
  'alipay.com'
  'alipayobjects.com'
  'aliyun.com'
  'aliyuncs.com'
  'aliyundrive.com'
  'amap.com'
  'antgroup.com'
  'ark.cn-beijing.volces.com'
  'baichuan-ai.com'
  'baidu.com'
  'baidubce.com'
  'baiducloud.com'
  'baiducontent.com'
  'bankcomm.com'
  'bankofchina.com'
  'bdimg.com'
  'bdstatic.com'
  'bilibili.com'
  'bilibili.tv'
  'bytedance.com'
  'cctv.com'
  'chinaz.com'
  'cmbchina.com'
  'cn'
  'cnbce.com'
  'cnblogs.com'
  'csdn.net'
  'ctrip.com'
  'deepseek.ai'
  'deepseek.com'
  'dianping.com'
  'didichuxing.com'
  'didiglobal.com'
  'dingtalk.com'
  'docer.com'
  'douban.com'
  'douyin.com'
  'douyu.com'
  'etao.com'
  'feishu.com'
  'fliggy.com'
  'foxmail.com'
  'hao123.com'
  'haosou.com'
  'huaweicloud.com'
  'huya.com'
  'hwclouds.com'
  'iqiyi.com'
  'iqiyipic.com'
  'jd.com'
  'jianshu.com'
  'jingdong.com'
  'jinritemai.com'
  'kingsoft.com'
  'kuaishou.com'
  'kugou.com'
  'le.com'
  'lenovocn.com'
  'licai.com'
  'lingyiwanwu.com'
  'meituan.com'
  'mgtv.com'
  'mi.com'
  'minimax.io'
  'myqcloud.com'
  'netease.com'
  'oschina.net'
  'pinduoduo.com'
  'qiniu.com'
  'qiniucdn.com'
  'qq.com'
  'qunar.com'
  'qwen.ai'
  'so.com'
  'sogou.com'
  'sohu.com'
  'stepfun.com'
  'suning.com'
  'taobao.com'
  'tcl.com'
  'tencentcloud.com'
  'tmall.com'
  'toutiao.com'
  'trip.com'
  'tudou.com'
  'ucweb.com'
  'vip.com'
  'volcengine.com'
  'wechat.com'
  'weibo.com'
  'wps.com'
  'xianyu.com'
  'xiaohongshu.com'
  'xinhuanet.com'
  'yi.com'
  'yinyuetai.com'
  'youku.com'
  'yy.com'
  'zhangzha.com'
  'zhihu.com'\n)

# ===== Tunnel exclude list (domain match: subdomains need explicit or *. prefix) =====
exclude=(\n  '126.com'
  '163.com'
  '2345.com'
  '37.com'
  '4399.com'
  'abchina.com'
  'acfun.com'
  'alibabacloud.com'
  'alicdn.com'
  'alipay.com'
  'alipayobjects.com'
  'aliyun.com'
  'aliyuncs.com'
  'aliyundrive.com'
  'amap.com'
  'antgroup.com'
  'ark.cn-beijing.volces.com'
  'baichuan-ai.com'
  'baidu.com'
  'baidubce.com'
  'baiducloud.com'
  'baiducontent.com'
  'bankcomm.com'
  'bankofchina.com'
  'bdimg.com'
  'bdstatic.com'
  'bilibili.com'
  'bilibili.tv'
  'bytedance.com'
  'cctv.com'
  'chat.deepseek.com'
  'chinaz.com'
  'cmbchina.com'
  'cn'
  'cnbce.com'
  'cnblogs.com'
  'csdn.net'
  'ctrip.com'
  'deepseek.ai'
  'deepseek.com'
  'dianping.com'
  'didichuxing.com'
  'didiglobal.com'
  'dingtalk.com'
  'docer.com'
  'douban.com'
  'douyin.com'
  'douyu.com'
  'etao.com'
  'feishu.com'
  'fliggy.com'
  'foxmail.com'
  'hao123.com'
  'haosou.com'
  'huaweicloud.com'
  'huya.com'
  'hwclouds.com'
  'iqiyi.com'
  'iqiyipic.com'
  'jd.com'
  'jianshu.com'
  'jingdong.com'
  'jinritemai.com'
  'jr.jd.com'
  'kingsoft.com'
  'kuaishou.com'
  'kugou.com'
  'lbs.amap.com'
  'le.com'
  'lenovocn.com'
  'licai.com'
  'lingyiwanwu.com'
  'mail.163.com'
  'mail.qq.com'
  'map.baidu.com'
  'meituan.com'
  'mgtv.com'
  'mi.com'
  'minimax.io'
  'music.163.com'
  'myqcloud.com'
  'netease.com'
  'oschina.net'
  'oss-cn-hangzhou.aliyuncs.com'
  'pinduoduo.com'
  'qiniu.com'
  'qiniucdn.com'
  'qq.com'
  'qunar.com'
  'qwen.ai'
  'qzone.qq.com'
  'so.com'
  'sogou.com'
  'sohu.com'
  'stepfun.com'
  'suning.com'
  'taobao.com'
  'tcl.com'
  'tencentcloud.com'
  'tieba.baidu.com'
  'tmall.com'
  'tongyi.aliyun.com'
  'toutiao.com'
  'trip.com'
  'tudou.com'
  'ucweb.com'
  'v.qq.com'
  'vip.com'
  'volcengine.com'
  'wechat.com'
  'weibo.com'
  'weixin.qq.com'
  'wps.com'
  'xianyu.com'
  'xiaohongshu.com'
  'xinhuanet.com'
  'yi.com'
  'yinyuetai.com'
  'youku.com'
  'yy.com'
  'zhangzha.com'
  'zhihu.com'\n)

echo "应用 DNS 回退列表 ($((${#fallback[@]})) 条)..."
for d in "${fallback[@]}"; do
  warp-cli dns fallback add "$d" >/dev/null 2>&1 || true
done

echo "应用隧道排除列表 ($((${#exclude[@]})) 条)..."
for d in "${exclude[@]}"; do
  warp-cli tunnel host add "$d" >/dev/null 2>&1 || true
done

echo "=== 完成。建议重启 WARP 使规则全量生效 ==="
echo "warp-cli disconnect && warp-cli connect"