# Requires: Cloudflare WARP client installed, warp-cli in PATH, run as Administrator
# Purpose: Apply domain-fallback + split-tunnel exclusion rules so that
#          domestic (.cn / major Chinese sites) bypass WARP, while foreign
#          LLM / search / blocked sites go through the WARP tunnel by default.
#
# Matching semantics (VERIFIED, do not assume):
#   - DNS fallback   = SUFFIX match -> bare "abc.com" covers all subdomains.
#                      List contains ONLY bare homepages + "cn". NO wildcards.
#   - Tunnel exclude = DOMAIN match -> bare "abc.com" does NOT cover subdomains;
#                      subdomains need "*.abc.com". List = homepage + *.homepage + "cn".
#   - "cn" (bare) covers ALL .cn at any level (e.g. baidu.cn, people.com.cn, x.y.cn).
#     Therefore no per-site .cn entries are needed; "cn" alone is the suffix catch-all.

$ErrorActionPreference = 'SilentlyContinue'

function Test-Warp {
    $reg = warp-cli registration show 2>&1
    if ($LASTEXITCODE -ne 0 -or ($reg -match 'not registered' -or $reg -match 'error')) {
        Write-Warning "warp-cli not ready / not registered. Run: warp-cli registration new"
        exit 1
    }
}
function Add-Fallback { param([string[]]$list)
    $n=0; foreach ($d in $list){ if((warp-cli dns fallback add $d 2>&1) -match 'Success'){ $n++ } }
    Write-Host "DNS fallback: added $n / $($list.Count)"
}
function Add-Exclude { param([string[]]$list)
    $n=0; foreach ($d in $list){ if((warp-cli tunnel host add $d 2>&1) -match 'Success'){ $n++ } }
    Write-Host "Tunnel exclude: added $n / $($list.Count)"
}

Test-Warp

# DNS fallback: bare homepages only (suffix match covers subdomains) + "cn"
$fallback = @(
    '126.com',
    '163.com',
    'abchina.com',
    'alipay.com',
    'aliyun.com',
    'aliyuncs.com',
    'amap.com',
    'baichuan-ai.com',
    'baidu.com',
    'bankcomm.com',
    'bankofchina.com',
    'bilibili.com',
    'bytedance.com',
    'ccb.com',
    'cctv.com',
    'chinaz.com',
    'cmbchina.com',
    'cn',
    'cnblogs.com',
    'csdn.net',
    'ctrip.com',
    'deepseek.ai',
    'deepseek.com',
    'dianping.com',
    'didiglobal.com',
    'dingtalk.com',
    'docer.com',
    'douban.com',
    'douyin.com',
    'douyu.com',
    'fliggy.com',
    'foxmail.com',
    'haier.com',
    'huaweicloud.com',
    'huya.com',
    'icbc.com',
    'iqiyi.com',
    'jd.com',
    'jianshu.com',
    'jingdong.com',
    'kuaishou.com',
    'kugou.com',
    'lingyiwanwu.com',
    'meituan.com',
    'mgtv.com',
    'mi.com',
    'minimax.io',
    'myqcloud.com',
    'netease.com',
    'oschina.net',
    'pinduoduo.com',
    'qq.com',
    'qunar.com',
    'qwen.ai',
    'sogou.com',
    'sohu.com',
    'stepfun.com',
    'suning.com',
    'taobao.com',
    'tcl.com',
    'tencentcloud.com',
    'tmall.com',
    'toutiao.com',
    'trip.com',
    'vip.com',
    'volcengine.com',
    'weibo.com',
    'weixin.qq.com',
    'wps.com',
    'xianyu.com',
    'xiaohongshu.com',
    'xinhuanet.com',
    'yi.com',
    'yinyuetai.com',
    'youku.com',
    'zhihu.com'
)

# Tunnel exclude: homepage + *.homepage (domain match needs wildcard for subdomains) + "cn"
$exclude  = @(
    '*.126.com',
    '*.163.com',
    '*.abchina.com',
    '*.alipay.com',
    '*.aliyun.com',
    '*.aliyuncs.com',
    '*.amap.com',
    '*.baichuan-ai.com',
    '*.baidu.com',
    '*.bankcomm.com',
    '*.bankofchina.com',
    '*.bilibili.com',
    '*.bytedance.com',
    '*.ccb.com',
    '*.cctv.com',
    '*.chinaz.com',
    '*.cmbchina.com',
    '*.cnblogs.com',
    '*.csdn.net',
    '*.ctrip.com',
    '*.deepseek.ai',
    '*.deepseek.com',
    '*.dianping.com',
    '*.didiglobal.com',
    '*.dingtalk.com',
    '*.docer.com',
    '*.douban.com',
    '*.douyin.com',
    '*.douyu.com',
    '*.fliggy.com',
    '*.foxmail.com',
    '*.haier.com',
    '*.huaweicloud.com',
    '*.huya.com',
    '*.icbc.com',
    '*.iqiyi.com',
    '*.jd.com',
    '*.jianshu.com',
    '*.jingdong.com',
    '*.kuaishou.com',
    '*.kugou.com',
    '*.lingyiwanwu.com',
    '*.meituan.com',
    '*.mgtv.com',
    '*.mi.com',
    '*.minimax.io',
    '*.myqcloud.com',
    '*.netease.com',
    '*.oschina.net',
    '*.pinduoduo.com',
    '*.qq.com',
    '*.qunar.com',
    '*.qwen.ai',
    '*.sogou.com',
    '*.sohu.com',
    '*.stepfun.com',
    '*.suning.com',
    '*.taobao.com',
    '*.tcl.com',
    '*.tencentcloud.com',
    '*.tmall.com',
    '*.toutiao.com',
    '*.trip.com',
    '*.vip.com',
    '*.volcengine.com',
    '*.weibo.com',
    '*.weixin.qq.com',
    '*.wps.com',
    '*.xianyu.com',
    '*.xiaohongshu.com',
    '*.xinhuanet.com',
    '*.yi.com',
    '*.yinyuetai.com',
    '*.youku.com',
    '*.zhihu.com',
    '126.com',
    '163.com',
    'abchina.com',
    'alipay.com',
    'aliyun.com',
    'aliyuncs.com',
    'amap.com',
    'baichuan-ai.com',
    'baidu.com',
    'bankcomm.com',
    'bankofchina.com',
    'bilibili.com',
    'bytedance.com',
    'ccb.com',
    'cctv.com',
    'chinaz.com',
    'cmbchina.com',
    'cnblogs.com',
    'csdn.net',
    'ctrip.com',
    'deepseek.ai',
    'deepseek.com',
    'dianping.com',
    'didiglobal.com',
    'dingtalk.com',
    'docer.com',
    'douban.com',
    'douyin.com',
    'douyu.com',
    'fliggy.com',
    'foxmail.com',
    'haier.com',
    'huaweicloud.com',
    'huya.com',
    'icbc.com',
    'iqiyi.com',
    'jd.com',
    'jianshu.com',
    'jingdong.com',
    'kuaishou.com',
    'kugou.com',
    'lingyiwanwu.com',
    'meituan.com',
    'mgtv.com',
    'mi.com',
    'minimax.io',
    'myqcloud.com',
    'netease.com',
    'oschina.net',
    'pinduoduo.com',
    'qq.com',
    'qunar.com',
    'qwen.ai',
    'sogou.com',
    'sohu.com',
    'stepfun.com',
    'suning.com',
    'taobao.com',
    'tcl.com',
    'tencentcloud.com',
    'tmall.com',
    'toutiao.com',
    'trip.com',
    'vip.com',
    'volcengine.com',
    'weibo.com',
    'weixin.qq.com',
    'wps.com',
    'xianyu.com',
    'xiaohongshu.com',
    'xinhuanet.com',
    'yi.com',
    'yinyuetai.com',
    'youku.com',
    'zhihu.com'
)

Add-Fallback $fallback
Add-Exclude  $exclude

Write-Host "=== Done. Restart WARP to apply fully: warp-cli disconnect ; warp-cli connect ==="
